#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
version: '3.3'
services: 
  webui:
    image: ${WEBUI_IMAGE}    
    networks:
      - openamtnetwork
    build:
      context: ./sample-web-ui
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      RPS_SERVER: https://localhost/rps
      MPS_SERVER: https://localhost/mps
    volumes:
      - ./sample-web-ui/nginx.conf:/etc/nginx/conf.d/default.conf  
  rps:
    image: ${RPS_IMAGE}
    networks:
      - openamtnetwork
    build:
      context: ./rps
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment: 
      RPS_USER: ${RPS_MPS_USER}
      RPS_PASSWORD: ${RPS_MPS_PASSWORD}
      RPS_CORS_ORIGIN: "*"
      RPS_CORS_HEADERS: ${CORS_HEADERS}
      RPS_CORS_METHODS: ${CORS_METHODS}
      RPS_CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
      RPS_MPS_SERVER: http://mps:3000
  mps:
    image: ${MPS_IMAGE}
    networks:
      - openamtnetwork
    build:
      context: ./mps
      dockerfile: ./Dockerfile
    ports: 
      - "${MPSPORT}:4433"
    env_file:
      - .env
    environment: 
      MPS_USERNAME: ${MPS_USER}
      MPS_PASS: ${MPS_PASSWORD}
      MPS_MPSXAPIKEY: ${MPS_XAPIKEY}
      MPS_CORS_ORIGIN: "*"
      MPS_CORS_HEADERS: ${CORS_HEADERS}
      MPS_CORS_METHODS: ${CORS_METHODS}
    volumes:
      - private-volume:/mps-microservice/private
  db:
    image: postgres
    networks:
      - openamtnetwork
    restart: always
    environment:
      POSTGRES_DB: ${RPS_DB_NAME}
      POSTGRES_USER: ${RPS_DB_USER}
      POSTGRES_PASSWORD: ${RPS_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - ./data:/docker-entrypoint-initdb.d
  vault:
    image: "vault"
    networks:
      - openamtnetwork
    ports: 
      - "8200:8200"
    environment: 
      VAULT_DEV_ROOT_TOKEN_ID: ${RPS_VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add: 
      - IPC_LOCK
  kong:
    image: kong:latest
    healthcheck:
      test:
        - CMD
        - nc
        - -z
        - localhost
        - "8443"
      retries: 10
    command: 
      - "kong"
      - "start"
      - "--vv"
    environment:
      - KONG_DATABASE=off
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_NGINX_DAEMON=off
      - KONG_DECLARATIVE_CONFIG=/home/kong/kong.yml
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_DNS_ORDER=LAST,A,CNAME
    networks:
      - openamtnetwork
    volumes:
      - ./kong.yaml:/home/kong/kong.yml
    ports:
      - "443:8443"
      - "8001:8001"
    restart: always
volumes:
    app-volume:
    private-volume:
networks: 
  openamtnetwork:
    driver: "bridge"
