apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
    app: kong
  name: {{ .Release.Name }}-kong
spec:
  ports:
  - port: 8001
    name: admin-http
    protocol: TCP
    targetPort: admin-http
  - port: 8444
    name: admin-https
    protocol: TCP
    targetPort: admin-https
  - port: 80
    name: proxy-http
    protocol: TCP
    targetPort: proxy-http
  - port: 443
    name: proxy-https
    protocol: TCP
    targetPort: proxy-https
  selector:
    {{- include "installServersChart.selectorLabels" . | nindent 4 }}
    app: kong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kong
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mps.replicaCount }}
  selector:
    matchLabels:
      {{- include "installServersChart.selectorLabels" . | nindent 6 }}
      app: kong
  template:
    metadata:
      labels:
        {{- include "installServersChart.labels" . | nindent 8 }}
        app: kong
    spec:
      {{- include "installServersChart.imagePullSecrets" . | nindent 6 }}
      volumes:
        - name: kong-config
          secret:
            secretName: {{ .Release.Name }}-kong-config
      containers:
        - name: kong
          image: {{ .Values.images.kong }}
          command:
          - kong
          - start
          - '--vv'
          env:
            - name: "KONG_DATABASE"
              value: "off"
            - name: "KONG_CASSANDRA_CONTACT_POINTS"
              value: "kong-database"
            - name: "KONG_ADMIN_LISTEN"
              value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
            - name: "KONG_NGINX_DAEMON"
              value: "off"
            - name: "KONG_DECLARATIVE_CONFIG"
              value: "/home/kong/kong.yml"
            - name: "KONG_PROXY_ERROR_LOG"
              value: "/dev/stderr"
            - name: "KONG_PROXY_ACCESS_LOG"
              value: "/dev/stdout"
            - name: "KONG_ADMIN_ACCESS_LOG"
              value: "/dev/stdout"
            - name: "KONG_ADMIN_ERROR_LOG"
              value: "/dev/stderr"
            - name: "KONG_DNS_ORDER"
              value: "LAST,A,CNAME"
            - name: "KONG_UPSTREAM_KEEPALIVE_POOL_SIZE"
              value: "0"
          ports:
            - containerPort: 8001
              name: admin-http
            - containerPort: 8444
              name: admin-https
            - containerPort: 8000
              name: proxy-http
            - containerPort: 8443
              name: proxy-https
          volumeMounts:
            - name: kong-config
              mountPath: /home/kong/kong.yml
              subPath: kong.yml
          livenessProbe:
            httpGet:
              path: /
              port: admin-http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 30
