apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
    app: mosquitto
  name: {{ .Release.Name }}-mosquitto-config
data:
  mosquitto.conf: |
    {{- tpl (.Files.Get "conf/mosquitto.conf") . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
    app: mosquitto
  name: {{ .Release.Name }}-mosquitto
spec:
  ports:
  - port: 1883
    name: mqtt
    protocol: TCP
    targetPort: mqtt
  - port: 9001
    name: websocket
    protocol: TCP
    targetPort: websocket
  selector:
    {{- include "installServersChart.selectorLabels" . | nindent 4 }}
    app: mosquitto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mosquitto
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mps.replicaCount }}
  selector:
    matchLabels:
      {{- include "installServersChart.selectorLabels" . | nindent 6 }}
      app: mosquitto
  template:
    metadata:
      labels:
        {{- include "installServersChart.labels" . | nindent 8 }}
        app: mosquitto
    spec:
      {{- include "installServersChart.imagePullSecrets" . | nindent 6 }}
      volumes:
        - name: mosquitto-config
          configMap:
            name: {{ .Release.Name }}-mosquitto-config
      containers:
        - name: mosquitto
          image: {{ .Values.images.mosquitto }}
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 9001
              name: websocket
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: admin-http
          #    scheme: HTTP
          #  timeoutSeconds: 1
          #  periodSeconds: 10
          #  successThreshold: 1
          #  failureThreshold: 3
          #  initialDelaySeconds: 30
