#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
    app: mpsrouter
  name: {{ .Release.Name }}-mpsrouter
spec:
  ports:
  - port: 8003
    name: mpsrouter
    protocol: TCP
    targetPort: 8003
  selector:
    app: mpsrouter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mpsrouter
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mpsrouter.replicaCount }}
  selector:
    matchLabels:
      app: mpsrouter
  template:
    metadata:
      annotations:
        kuma.io/direct-access-services: "mps_default_svc_3000"
      labels:
        {{- include "installServersChart.labels" . | nindent 8 }}
        app: mpsrouter
    spec:
      {{- include "installServersChart.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: mpsrouter
          securityContext:
            runAsUser: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          image:  {{ .Values.images.mpsrouter }}
          readinessProbe:
            exec:
              command: ["/app","--health"]
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: "MPS_CONNECTION_STRING"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: mpsdb-connection-string
            - name: "PORT"
              value: "8003"
            - name: "MPS_HOST"
              value: "{{ .Release.Name }}-mps"
            - name: "MPS_PORT"
              value: "3000"
          ports:
            - containerPort: 8003
              name: mpsrouter
