{{- $postgresPassword := (include "common.secrets.passwords.manage.plain" (dict "secret" .Values.postgresql.auth.existingSecret "key" "postgres-password" "providedValues" (list "postgresql.auth.postgresPassword") "context" $)) -}}
{{- $jwtSecret := (include "common.secrets.passwords.manage.plain" (dict "secret" (printf "%s-secret" .Release.Name) "key" "jwt-secret" "length" 32 "providedValues" (list "mps.jwtSecret") "context" $)) -}}
{{- $jwtIssuer := .Values.mps.jwtIssuer -}}
{{- $tplRoot := dict "root" . "Template" .Template "jwtIssuer" $jwtIssuer "jwtSecret" $jwtSecret -}}

apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
  name: {{ .Values.postgresql.auth.existingSecret | quote }}
data:
  postgres-password: {{ $postgresPassword | b64enc | quote }}
  password: {{ include "common.secrets.passwords.manage" (dict "secret" .Values.postgresql.auth.existingSecret "key" "password" "providedValues" (list "postgresql.auth.password") "context" $) }}
  replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" .Values.postgresql.auth.existingSecret "key" "replication-password" "providedValues" (list "postgresql.auth.replicationPassword") "context" $) }}

---

apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-secret
data:
  mpsdb-connection-string: {{ (printf "postgresql://postgres:%s@%s:5432/mpsdb" $postgresPassword (printf "%s-postgresql" .Release.Name)) | b64enc | quote }}
  rpsdb-connection-string: {{ (printf "postgresql://postgres:%s@%s:5432/rpsdb" $postgresPassword (printf "%s-postgresql" .Release.Name)) | b64enc | quote }}
  jwt-secret: {{ $jwtSecret | b64enc | quote }}
  jwt-issuer: {{ $jwtIssuer | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "installServersChart.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-kong-config
data:
  kong.yml: {{ tpl (.Files.Get "conf/kong.yaml") $tplRoot | b64enc | quote }}

